### ISSUE TITLE
Can't filter a resource

### ISSUE THREAD

**Issue by alexbfree** [daliwali/fortune#61]
I have a simple resource defined as follows:

    ...
    .resource('event', {
        time: Date, 
        subject_id:String,
        user_id:String,
        type: String
      })
    ...

I can GET
http://localhost:8090/events
but filtering does not seem to be happening:

http://localhost:8090/events?type=typeA
http://localhost:8090/events?subject_id=2
http://localhost:8090/events?user_id=abc
These all return the full list of events, even though these attribute values only apply to a subset of the data.

How is filtering supposed to work with fortune? Or is it broken/not implemented? I notice JSON API spec says it is optional.

**Comment by daliwali** [comment]
It isn't implemented in the current version on master, and there is a rewrite branch going on which seeks to address this and many shortcomings which I didn't foresee. Part of the problem is how the JSON API serializer and http router is so coupled with everything, and the JSON API spec itself has gone through a lot of churn during the time I was working on the version that's on master right now. So the future version will be decoupled from any spec to 1) make it possible to maintain separate serializers and 2) make this project relevant to people who don't want to be locked in to json api over http. so basically don't use it until the rewrite is done :tada:

**Comment by alexbfree** [comment]
sounds good. meantime i will write my own filtering. thanks for the explanation.

**Comment by alexbfree** [comment]
PS @daliwali what is the schedule for the rewrite, when do we expect it to be ready for use?

**Comment by daliwali** [comment]
@alexbfree what's (almost) done is the core functionality, still have to finish that, write tests and adapters/serializers. aiming for an alpha release next month.

**Comment by alexbfree** [comment]
Thanks, I look forward to it! Good luck!

On Tue, Jan 27, 2015 at 5:01 PM, Dali Zheng <notifications@github.com>
wrote:

> @alexbfree <https://github.com/alexbfree> what's (almost) done is the
> core functionality, still have to finish that, write tests and
> adapters/serializers. aiming for an alpha release next month.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/daliwali/fortune/issues/61#issuecomment-71684407>.
>



-- 
Alex Bowyer - alex.bowyer@gmail.com - @alexbfree
<http://www.twitter.com/alexbfree>
Interaction Designer, Citizen Scientist, Web Developer

alexbowyer.com
<http://alexbowyer.com/?utm_source=alex&utm_medium=emailsig&utm_content=homepage&utm_campaign=none>
 - Blog <http://blog.alexbowyer.com/> - WeReddit Podcast
<http://www.wereddit.com/?utm_source=alex&utm_medium=emailsig&utm_content=homepage&utm_campaign=none>
 - Zooniverse <http://www.zooniverse.org/>
